<a href="https://colab.research.google.com/github/lmerasoc/Analisis-de-datos-Bootcamp/blob/main/Lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PARTE 1
-	Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame

In [1]:
import pandas as pd;
import numpy as np;

In [2]:
data = {'Nombre': ['Ana', 'Carlos', 'Lucía', 'Javier','Marta', 'Diego', 'Paula', 'Andrés'],
 'Profesión': ['Ingeniera', 'Doctor', 'Diseñadora', 'Abogado','Contadora', 'Profesor', 'Arquitecta', 'Periodista'],
 'País': ['Colombia', 'México', 'España', 'Argentina','Perú', 'Chile', 'Ecuador', 'Uruguay']}
df = pd.DataFrame(data)
print(df)

   Nombre   Profesión       País
0     Ana   Ingeniera   Colombia
1  Carlos      Doctor     México
2   Lucía  Diseñadora     España
3  Javier     Abogado  Argentina
4   Marta   Contadora       Perú
5   Diego    Profesor      Chile
6   Paula  Arquitecta    Ecuador
7  Andrés  Periodista    Uruguay


-	Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.

In [4]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving data.json to data.json


In [11]:
df=pd.read_json('data.json')
df2=df.head()
print(df2.to_string())

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [12]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv


In [14]:
df3=pd.read_csv('data.csv')
df4=df3.head()
print(df4.to_string())

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


-	Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.

In [19]:
import pandas as pd;
import numpy as np;
fechas=pd.date_range("2020-01-01",periods=100,freq="ME")
print(fechas)

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
      

In [23]:
import pandas as pd;
import numpy as np;
df=pd.DataFrame(np.random.randn(100,8))
print(df.head(10))

          0         1         2         3         4         5         6  \
0 -1.185067  0.361197  0.661160 -0.955016  0.114002  0.289201  1.515325   
1 -0.660729 -1.190940  0.414481 -0.550153  0.177203  0.620702 -1.663429   
2  1.195838  0.942200 -0.274831 -0.519655  0.451985  0.551246 -0.000610   
3  0.024116  1.471241 -0.759960  1.430161  0.096715  1.061860  0.141255   
4 -1.008745 -1.603451  0.279456 -0.727983  0.175203 -1.439277 -0.019242   
5  0.260819 -1.866492  1.955163 -1.889492 -0.225359  0.640345 -1.136934   
6  0.565936 -0.910214  1.215689  1.160441 -0.540604 -0.036885  0.500871   
7  0.879490 -0.714778 -0.121262  0.882168 -0.272288  0.274786 -0.694776   
8  0.656745  1.160001  0.877171  0.885316 -0.255005  0.611716 -0.362133   
9  1.421760  0.032808 -1.379211  0.735241  0.699344 -1.638654 -0.588161   

          7  
0  1.135676  
1  0.222278  
2 -0.114117  
3  1.469279  
4 -0.596359  
5 -0.000372  
6  1.698077  
7 -0.524420  
8 -0.002076  
9  1.376342  


In [25]:
df.describe()

0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.080067    0.045851    0.101845   -0.027135    0.190459   -0.035322   
std      0.937000    1.037145    0.998955    1.069003    1.091655    1.014786   
min     -2.897648   -2.433792   -2.228002   -2.591283   -2.517310   -2.232659   
25%     -0.550496   -0.699939   -0.569444   -0.853208   -0.252771   -0.799965   
50%      0.076636    0.024667   -0.109135    0.044705    0.356238    0.063548   
75%      0.669119    0.811696    0.632596    0.792629    0.818703    0.625613   
max      2.395923    2.318909    2.294303    2.794155    2.599758    2.261629   

                6           7  
count  100.000000  100.000000  
mean    -0.140904    0.089510  
std      0.971904    0.873223  
min     -2.292210   -1.645965  
25%     -0.814842   -0.675999  
50%     -0.131125    0.226472  
75%      0.597567    0.713432  
max      2.321459    2.270273

from matplotlib import pyplot as plt
_df_0[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3[3].plot(kind='hist', bins=20, title=3)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x=2, y=3, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x=3, y=4, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11[3].plot(kind='line', figsize=(8, 4), title=3)
plt.gca().spines[['top', 'right']].set_visible(False)

PARTE 2
-	Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.

In [33]:
import numpy as np
A1=np.arange(1,11)
A1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
Resultados=A1.sum(), A1.mean(), A1.max()
print(Resultados)

(np.int64(55), np.float64(5.5), np.int64(10))


-	Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6

In [42]:
A2=np.zeros((3,4))
A2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
A2 = A2.reshape((2, 6))
print(A2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


-	Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

In [52]:
Matriz=np.random.randn(3,3)
print(Matriz)

[[ 2.34123898  0.58470357  0.64297813]
 [-0.26523605  1.84862295 -0.56181783]
 [ 0.9677154  -0.9080348   1.4073532 ]]


In [53]:
Matrizt=Matriz.transpose()
print(Matrizt)

[[ 2.34123898 -0.26523605  0.9677154 ]
 [ 0.58470357  1.84862295 -0.9080348 ]
 [ 0.64297813 -0.56181783  1.4073532 ]]


-	Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado.

In [57]:
A4=np.arange(20,25)
A5=np.array([6,7,8,9,10])
A6=np.concatenate((A4,A5))
print(A6)

[20 21 22 23 24  6  7  8  9 10]
